export const certificateCopy = {
  title: "SKILL ISSUE",
  certified: "CERTIFIED",
  subtitle: "Officially unofficial. Absolutely earned.",
  belongsTo: "THIS CARD BELONGS TO",
  emptyName: "ENTER YOUR NAME",
  certificateNo: "CERTIFICATE NO. SIC-2026",
  committee: "the pencil committee ✎",
  approved: "APPROVED",
  stamp: "OFFICIALLY UNOFFICIAL",
  generatedBy: "GENERATED BY skill-issue-certified-generator.awarin.art",
  ariaLabel: "Skill Issue Certified card preview",
} as const;
